INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(1,1);
INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(2,2);
INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(3,1);
INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(4,1);
INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(5,2);
INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(6,2);
INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(7,2);
INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(8,3);
INSERT INTO ase.Issue_has_Project(Issue_idIssue,Project_idProject)VALUES(9,1);
